version: '3'

services:
    swoft:
       image: swoft/swoft:latest
#       build: ./
       ports:
         - "9501:9501"
       volumes:
         - ./:/var/www/mix
       stdin_open: true 
       tty: true
       privileged: true
#       entrypoint: ["php", "/var/www/mix/bin/mix-httpd","service", "start"]
